### ISSUE TITLE
Dependency to pandas not resolved?

### ISSUE THREAD

**Issue by 1kastner** [nobodyinperson/python3-netatmo#1]
I tried to install netatmo via pip and the following error happened:

    C:\WINDOWS\system32>pip --version
    pip 9.0.1 from c:\program files (x86)\python\lib\site-packages (python 3.6)
    
    C:\WINDOWS\system32>pip install netatmo
    Collecting netatmo
      Downloading netatmo-0.1.3.tar.gz
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "XXXX\netatmo\setup.py", line 7, in <module>
            from netatmo import __version__
          File "XXXX\netatmo\netatmo\__init__.py", line 8, in <module>
            from . import api
          File "XXXX\netatmo\netatmo\api\__init__.py", line 8, in <module>
            from . import authentication
          File "XXXX\netatmo\netatmo\api\authentication.py", line 12, in <module>
            from . import requests
          File "XXXX\netatmo\netatmo\api\requests.py", line 11, in <module>
            from . import responsetypes
          File "XXXX\netatmo\netatmo\api\responsetypes.py", line 6, in <module>
            import pandas as pd
        ModuleNotFoundError: No module named 'pandas'
    
        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in XXXX

I used the standard Python interpreter as it is retrieved from www.python.org

**Comment by nobodyinperson** [comment]
I'm on it. It's because I import the package itself during installation. Not a good idea.

**Comment by 1kastner** [comment]
This is just a general remark as I prefer miniconda in my current setup and for that it looks like it works well (except the messages mentioned in issue #2) .

**Comment by nobodyinperson** [comment]
Should be fixed as of 9ac3f90. There is a new version v0.1.4 on PyPi.

**Comment by 1kastner** [comment]
The installation now worked like a charm!
